FROM ubuntu:24.04
RUN apt-get update && apt-get install -y openjdk-21-jdk \
    wget && \
    wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz &&\
    tar -xvzf apache-maven-3.9.9-bin.tar.gz &&\
    mv apache-maven-3.9.9 /opt/
    

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV MAVEN_HOME=/opt/apache-maven-3.9.9
ENV PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH

CMD ["sh", "-c", "java --version && mvn --version"]

