
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - AppNetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5


  ## Backend bằng Spring Boot
  backend:
    build: ./Backend
    container_name: java-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/testdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - AppNetwork


## Frontend bằng Angular
  frontend:
    container_name: angular-app
    ports:
      - "4200:4200"
    build: ./Frontend
    volumes:
      - ./Frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - AppNetwork
    command: npm start
    depends_on:
      backend:
        condition: service_started
      
volumes:
  mysql-data:

networks:
  AppNetwork: 
   
